Repository lblod/frontend-reglementaire-bijlage, pull requests merged in 2022-09, with the labels that each got.

#11 Addition of an environment banner
  app/controllers/application.js
  app/styles/_shame.scss
  app/styles/app.scss
  app/templates/application.hbs
  config/environment.js
  package-lock.json
  package.json
Labels: enhancement

#12 Feature/publication
  app/components/app-chrome.hbs
  app/components/app-chrome.js
  app/components/rdfa-editor-container.js
  app/controllers/edit.js
  app/controllers/list.js
  app/controllers/publish.js
  app/models/editor-document.js
  app/models/regulatory-statement.js
  app/router.js
  app/routes/list.js
  app/routes/publish.js
  app/services/mu-task.js
  app/templates/edit.hbs
  app/templates/list.hbs
  app/templates/publish.hbs
  app/utils/constants.js
  package-lock.json
  package.json
  tests/unit/routes/publish-test.js
  translations/en-us.yaml
  translations/nl-be.yml
Labels: enhancement

#13 Introduce new version of table of contents plugin
  app/components/rdfa-editor-container.js
  app/controllers/edit.js
  app/utils/constants.js
  package-lock.json
  package.json
Labels: enhancement

#16 Add more validations to codelist creation and edit workflow
  app/components/codelist-form.hbs
  app/components/codelist-form.js
  app/components/codelist-option-form.hbs
  app/components/codelist-option-form.js
  app/templates/codelists-management/codelist.hbs
  app/validations/codelist-option.js
  translations/en-us.yaml
  translations/nl-be.yml
Labels: enhancement

#17 Update ember-data to 3.28
  app/components/codelist-form.hbs
  app/components/codelist-form.js
  app/models/skos-concept.js
  package-lock.json
  package.json
  tests/unit/models/code-list-test.js
Labels: internal

#18 Add insert variable plugin
  app/components/rdfa-editor-container.js
  app/styles/app.scss
  package-lock.json
  package.json
Labels: enhancement

#20 add the variable plugin config
  README.md
  config/environment.js
Labels: bug

#21 Save before going to publish
  app/components/app-chrome.hbs
  app/controllers/edit.js
  app/templates/edit.hbs
Labels: bug

#23 bump insert-variable-plugin to 0.2.1
  package-lock.json
  package.json
Labels: bug

#19 Improvements on publication UX according to Jira
  app/controllers/list.js
  app/controllers/publish.js
  app/routes/edit.js
  app/routes/publish.js
  app/templates/publish.hbs
Labels: enhancement
