Repository lblod/frontend-reglementaire-bijlage, pull requests merged in 2022-10, with the labels that each got.

#25 Convert codelist creator to form and automatically focus the first input
  app/components/codelist-option-form.hbs
  package-lock.json
  package.json
Labels: enhancement

#26 Improve translations and fill in missing translations
  app/components/app-chrome.hbs
  app/components/editor-document-title.hbs
  app/components/static-page.hbs
  app/instance-initializers/intl.js
  app/templates/application.hbs
  app/templates/codelists-management/codelist.hbs
  app/templates/codelists-management/edit.hbs
  app/templates/codelists-management/index.hbs
  app/templates/codelists-management/new.hbs
  app/templates/edit.hbs
  app/templates/list.hbs
  app/templates/login.hbs
  app/templates/mock-login.hbs
  app/templates/publish.hbs
  app/templates/switch-login.hbs
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#24 Bump generate-template-plugin
  package-lock.json
  package.json
Labels: internal

#27 Add additional prefixes and change reglementaire bijlage uri
  app/components/rdfa-editor-container.js
  app/config/editor-document-default-context.js
  app/controllers/edit.js
  app/templates/edit.hbs
Labels: enhancement

#30 Bugfix: ensure sparql page is scrollable
  app/templates/sparql.hbs
Labels: bug

#31 Rework publish page a bit and remove inline styles
  app/templates/index.hbs
  app/templates/publish.hbs
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#34 Bump generate template plugin to 0.1.5
  package-lock.json
  package.json
Labels: internal

#33 Added created on to codelist options and sort on that
  app/components/codelist-form.js
  app/controllers/codelists-management/codelist.js
  app/models/skos-concept.js
  app/templates/codelists-management/codelist.hbs
Labels: enhancement

#36 Ensure document previews on publish page have correct styling.
  app/templates/publish.hbs
Labels: bug

#35 Add max height to publish page cards
  app/styles/app.scss
  app/templates/publish.hbs
Labels: enhancement

#38 Add template-variable-plugin and disable location type variable
  app/components/rdfa-editor-container.js
  package-lock.json
  package.json
Labels: enhancement

#37 Cleanup of package.json
  app/components/rdfa-editor-container.js
  package-lock.json
  package.json
Labels: internal

#41 Refresh data when a regulatory statement has been removed or published
  app/controllers/list.js
  app/controllers/publish.js
  app/models/regulatory-attachment-publication-task.js
  app/routes/list.js
  app/routes/publish.js
  app/services/mu-task.js
Labels: enhancement

#43 Navigation of publish page and addition of `published` notification
  app/controllers/publish.js
  app/templates/publish.hbs
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#32 Save document title after editing it
  app/components/app-chrome.hbs
  app/components/app-chrome.js
  app/components/editor-document-title.hbs
  app/components/editor-document-title.js
Labels: bug
