Repository lblod/frontend-reglementaire-bijlage, pull requests merged in 2023-07, with the labels that each got.

#113 GN-4378 Revalidate codelist options list when changing the label
  app/components/codelist-form.hbs
  app/components/codelist-form.js
Labels: bug

#111 Implement new TOC scrolling functionality
  app/controllers/regulatory-attachments/edit.js
  app/controllers/snippets-management/edit/edit-snippet.js
Labels: enhancement

#129 Update @lblod/ember-rdfa-editor-lblod-plugins to 8.4.0
  app/commands/insert-title.js
  app/components/insert-title-card.hbs
  app/components/insert-title-card.js
  app/controllers/regulatory-attachments/edit.js
  app/controllers/snippets-management/edit/edit-snippet.js
  app/templates/regulatory-attachments/edit.hbs
  app/templates/snippets-management/edit/edit-snippet.hbs
  app/utils/editor-nodes.js
  package-lock.json
  package.json
Labels: internal
