Repository lblod/frontend-reglementaire-bijlage, pull requests merged in 2023-06, with the labels that each got.

#85 fixed currrentSession.group can be undefined
  app/controllers/edit.js
Labels: bug

#81 adding labels to options of codelist via the codelist edit/create form
  app/components/app-chrome.hbs
  app/components/codelist-form.hbs
  app/components/codelist-form.js
  app/components/codelist-option-form.hbs
  app/components/codelist-option-form.js
  app/controllers/codelists-management/codelist.js
  app/controllers/codelists-management/index.js
  app/models/skos-concept.js
  app/router.js
  app/routes/codelists-management/codelist.js
  app/routes/codelists-management/index.js
  app/styles/_breadcrumbs.scss
  app/styles/app.scss
  app/templates/application.hbs
  app/templates/codelists-management.hbs
  app/templates/codelists-management/codelist.hbs
  app/templates/codelists-management/edit.hbs
  app/templates/codelists-management/index.hbs
  app/templates/codelists-management/new.hbs
  app/templates/edit.hbs
  app/templates/list.hbs
  app/templates/publish.hbs
  app/utils/changeset.js
  app/utils/strings.js
  app/validations/codelist-option.js
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#95 Add woodpecker config file to verify PRs
  .woodpecker/.verify-pr.yml
  app/components/app-chrome.hbs
  app/templates/application.hbs
  app/templates/index.hbs
  app/templates/legal/accessibilitystatement.hbs
  app/templates/legal/cookiestatement.hbs
  app/templates/legal/disclaimer.hbs
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: internal

#87 Feature/snippets
  app/components/app-chrome.hbs
  app/components/app-chrome.js
  app/components/editor-document-title.hbs
  app/components/editor-document-title.js
  app/components/snippet-list-form.hbs
  app/components/snippet-list-form.js
  app/controllers/snippets-management/edit/edit-snippet.js
  app/controllers/snippets-management/edit/index.js
  app/controllers/snippets-management/index.js
  app/helpers/limit-content.js
  app/models/snippet-list.js
  app/router.js
  app/routes/snippets-management.js
  app/routes/snippets-management/edit.js
  app/routes/snippets-management/edit/edit-snippet.js
  app/routes/snippets-management/index.js
  app/routes/snippets-management/new.js
  app/styles/_c-app-chrome.scss
  app/styles/_shame.scss
  app/styles/app.scss
  app/templates/edit.hbs
  app/templates/index.hbs
  app/templates/snippets-management/edit/edit-snippet.hbs
  app/templates/snippets-management/edit/index.hbs
  app/templates/snippets-management/index.hbs
  app/templates/snippets-management/new.hbs
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#99 Update editor plugins to 8.0.1
  app/controllers/edit.js
  app/controllers/snippets-management/edit/edit-snippet.js
  package-lock.json
  package.json
Labels: internal

#101 Fix type translation on codelist overview page
  app/templates/codelists-management/index.hbs
Labels: bug

#108 Update `@lblod/ember-rdfa-editor` to 3.10
  package-lock.json
  package.json
Labels: internal

#109 GN-4312 make document title more distinct from title
  app/components/insert-title-card.js
  app/styles/_shame.scss
  app/templates/edit.hbs
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#110 Update `@lblod/ember-rdfa-editor-lblod-plugins` to 8.1.0
  package-lock.json
  package.json
Labels: internal

#121 Add number node and number view so the number variable is not broken
  app/controllers/edit.js
  app/controllers/snippets-management/edit/edit-snippet.js
Labels: bug

#120 Use AuModal for the modal shown when leaving a route
  app/components/codelist-form.hbs
  app/components/confirm-route-leave.hbs
  app/components/confirm-route-leave.js
  app/templates/edit.hbs
  app/templates/snippets-management/edit/edit-snippet.hbs
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement
