Repository lblod/frontend-reglementaire-bijlage, pull requests merged in 2023-04, with the labels that each got.

#73 "insert" card should be collapsible but open by default
  app/templates/edit.hbs
Labels: enhancement

#71 Use new ember-concurrency api
  app/components/codelist-form.js
  app/components/codelist-option-form.js
  app/controllers/codelists-management/index.js
  app/controllers/edit.js
  app/controllers/list.js
  app/controllers/mock-login.js
  app/controllers/publish.js
  app/services/mu-task.js
Labels: internal

#75 Fix missing translation issue
  app/templates/codelists-management/index.hbs
Labels: bug

#76 Add au-modal-container to application template and disable deprecation warning
  app/templates/application.hbs
  ember-cli-build.js
Labels: internal
