Repository lblod/frontend-reglementaire-bijlage, pull requests merged in 2023-09, with the labels that each got.

#180 Move to changesets for changelog management
  .changeset/README.md
  .changeset/config.json
  .changeset/rich-maps-own.md
  .release-it.json
  .woodpecker/.changeset.yml
  CONTRIBUTING.md
  package-lock.json
  package.json
Labels: internal

#174 GN-4330: allow single/multiselect specification per codelist instance
  .changeset/sour-otters-hide.md
  app/components/codelist-form.hbs
  app/components/codelist-form.js
  app/models/code-list.js
  app/templates/codelists-management/index.hbs
  app/utils/constants.js
  package-lock.json
  package.json
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#182 Add translations to variable-insert dropdown
  .changeset/fair-ties-rule.md
  app/controllers/regulatory-attachments/edit.js
  app/controllers/snippets-management/edit/edit-snippet.js
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: bug

#189 Fix website url in footer (hotfix)
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: bug

#190 Fix website url in footer
  .changeset/plenty-dodos-happen.md
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: bug
