Repository lblod/frontend-reglementaire-bijlage, pull requests merged in 2023-05, with the labels that each got.

#77 Add chrome and firefox hacks plugin and last key pressed plugin
  app/components/rdfa-editor-container.hbs
  app/components/rdfa-editor-container.js
  package-lock.json
  package.json
Labels: bug

#78 activate new text plugins
  app/controllers/edit.js
  app/templates/edit.hbs
Labels: enhancement

#82 Remove/replace deprecated code
  app/adapters/application.js
  app/components/codelist-form.js
  app/controllers/codelists-management/codelist.js
  app/controllers/mock-login.js
  app/models/account.js
  app/models/administrative-unit.js
  app/models/attachment.js
  app/models/code-list.js
  app/models/concept-scheme.js
  app/models/concept.js
  app/models/document-container.js
  app/models/editor-document.js
  app/models/governing-body.js
  app/models/mapping.js
  app/models/published-regulatory-attachment-container.js
  app/models/published-regulatory-attachment.js
  app/models/regulatory-attachment-publication-task.js
  app/models/shape.js
  app/models/skos-concept.js
  app/models/user.js
  app/modifiers/yasgui.js
  app/templates/mock-login.hbs
  package-lock.json
  package.json
Labels: internal
