Repository lblod/frontend-reglementaire-bijlage, pull requests merged in 2024-11, with the labels that each got.

#294 GN-5150: configure `emberApplication` prosemirror plugin
  .changeset/spotty-plants-jump.md
  app/components/rdfa-editor-container.js
Labels: bug

#298 Update editor-plugins to version 26.0.1
  .changeset/mighty-actors-invite.md
  .changeset/tasty-brooms-tell.md
  app/templates/snippet-management/edit/edit-snippet.hbs
  app/templates/template-management/edit.hbs
  package-lock.json
  package.json
Labels: internal

#303 Fix http error when opening templates
  .changeset/purple-cameras-change.md
  app/controllers/template-management/edit.js
  app/routes/template-management/edit.js
Labels: bug

#301 Feat/regenerate variable uris
  .changeset/warm-months-rest.md
  app/components/regenerate-variable-uris.hbs
  app/components/regenerate-variable-uris.js
  app/templates/snippet-management/edit/edit-snippet.hbs
  app/templates/template-management/edit.hbs
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement
